-- mateusz poponczyk
-- ==============================================================================
-- CONSOLIDATED STRICT MIGRATION BUNDLE
-- Generated by Antigravity
-- Timestamp: 2026-02-16 21:00:00 UTC
--
-- INSTRUCTIONS:
-- 1. Copy this entire block.
-- 2. Paste into Supabase SQL Editor.
-- 3. Run.
--
-- INCLUDES:
-- 1. 2026-02-15_01_business_hierarchy_schema.sql
-- 2. 2026-02-15_02_business_hierarchy_rpc.sql
-- 3. 2026-02-15_03_business_hierarchy_rbac_rpc.sql
-- 4. 2026-02-15_edit_locks.sql
-- 5. 20260216164354_2fa.sql (Hardened)
-- 6. remediate_permissions.sql
-- ==============================================================================


BEGIN;
-- Enable pgcrypto immediately
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Part 1: Business Hierarchy Schema
-- ------------------------------------------------------------------------------
-- 1. Permissions Extension
alter table public.permissions 
add column if not exists scope text not null default 'tenant' check (scope in ('tenant', 'company'));

create index if not exists idx_permissions_scope on public.permissions(scope);

-- 2. Groups (Tenant-Scoped)
create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  name text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(tenant_id, name),
  unique(id, tenant_id) -- Required for Composite FK
);
alter table public.groups enable row level security;
alter table public.groups force row level security;

create table if not exists public.group_members (
  group_id uuid,
  user_id uuid references auth.users(id) on delete cascade,
  tenant_id uuid,
  created_at timestamptz default now(),
  primary key (group_id, user_id),
  foreign key (group_id, tenant_id) references public.groups(id, tenant_id) on delete cascade
);
alter table public.group_members enable row level security;
alter table public.group_members force row level security;

-- 3. Core Hierarchy Tables (Strict + RLS)

-- 3.1 Organizations
create table if not exists public.organizations (
  id uuid default gen_random_uuid() primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  name text not null,
  owner_group_id uuid not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(tenant_id, name),
  unique(id, tenant_id), -- Required for Composite FK
  foreign key (owner_group_id, tenant_id) references public.groups(id, tenant_id) -- Strict Tenant Match
);
alter table public.organizations enable row level security;
alter table public.organizations force row level security;

-- 3.2 Companies
create table if not exists public.companies (
  id uuid default gen_random_uuid() primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  name text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(tenant_id, name),
  unique(id, tenant_id) -- Required for Composite FK
);
alter table public.companies enable row level security;
alter table public.companies force row level security;

-- Link: Organization <-> Company
create table if not exists public.org_companies (
  organization_id uuid,
  company_id uuid,
  tenant_id uuid not null,
  primary key (organization_id, company_id),
  foreign key (organization_id, tenant_id) references public.organizations(id, tenant_id) on delete cascade,
  foreign key (company_id, tenant_id) references public.companies(id, tenant_id) on delete cascade
);
alter table public.org_companies enable row level security;
alter table public.org_companies force row level security;

-- 3.3 Projects
create table if not exists public.projects (
  id uuid default gen_random_uuid() primary key,
  tenant_id uuid not null,
  organization_id uuid not null,
  name text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(tenant_id, organization_id, name),
  unique(id, tenant_id), -- Required for Composite FK
  foreign key (organization_id, tenant_id) references public.organizations(id, tenant_id) on delete restrict,
  foreign key (tenant_id) references public.tenants(id) on delete cascade
);
alter table public.projects enable row level security;
alter table public.projects force row level security;

-- Link: Project <-> Company (Invariant Enforced)
create table if not exists public.project_companies (
  project_id uuid,
  company_id uuid,
  tenant_id uuid not null,
  primary key (project_id, company_id),
  unique(project_id, company_id, tenant_id), -- For composite reference
  foreign key (project_id, tenant_id) references public.projects(id, tenant_id) on delete cascade,
  foreign key (company_id, tenant_id) references public.companies(id, tenant_id) on delete cascade
);
alter table public.project_companies enable row level security;
alter table public.project_companies force row level security;

-- Trigger: Enforce Org Membership for Project Companies (SECURITY DEFINER)
create or replace function public.enforce_project_company_org_match() returns trigger 
security definer
set search_path = public, extensions, auth
as $$
declare
  v_org_id uuid;
begin
  select organization_id into v_org_id from public.projects where id = NEW.project_id;
  if not exists (
      select 1 from public.org_companies 
      where organization_id = v_org_id 
      and company_id = NEW.company_id
      and tenant_id = NEW.tenant_id -- Strict Tenant Check
  ) then
    raise exception 'Company must belong to the Project Organization';
  end if;
  return NEW;
end;
$$ language plpgsql;
revoke all on function public.enforce_project_company_org_match() from public, anon;

drop trigger if exists trg_project_companies_org_check on public.project_companies;
create trigger trg_project_companies_org_check
before insert on public.project_companies
for each row execute function public.enforce_project_company_org_match();

-- 3.4 Service Offerings
create table if not exists public.service_offerings (
  id uuid default gen_random_uuid() primary key,
  tenant_id uuid not null,
  project_id uuid not null,
  name text not null,
  owner_group_id uuid not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(tenant_id, project_id, name),
  unique(id, tenant_id), -- Required for Composite FK
  foreign key (project_id, tenant_id) references public.projects(id, tenant_id) on delete restrict,
  foreign key (owner_group_id, tenant_id) references public.groups(id, tenant_id), -- Strict Tenant Match
  foreign key (tenant_id) references public.tenants(id) on delete cascade
);
alter table public.service_offerings enable row level security;
alter table public.service_offerings force row level security;

-- Link: Service Offering <-> Companies (Composition)
create table if not exists public.service_offering_companies (
  service_offering_id uuid,
  company_id uuid,
  tenant_id uuid not null,
  primary key (service_offering_id, company_id),
  foreign key (service_offering_id, tenant_id) references public.service_offerings(id, tenant_id) on delete cascade,
  foreign key (company_id, tenant_id) references public.companies(id, tenant_id) on delete cascade
);
alter table public.service_offering_companies enable row level security;
alter table public.service_offering_companies force row level security;

-- Trigger: Enforce Project Membership for Service Offering Companies (SECURITY DEFINER)
create or replace function public.enforce_offering_company_project_match() returns trigger 
security definer
set search_path = public, extensions, auth
as $$
declare
  v_project_id uuid;
begin
  select project_id into v_project_id from public.service_offerings where id = NEW.service_offering_id;
  -- Company must be in project_companies for this project
  if not exists (
      select 1 from public.project_companies 
      where project_id = v_project_id 
      and company_id = NEW.company_id
      and tenant_id = NEW.tenant_id -- Strict Tenant Check
  ) then
     raise exception 'Company must belong to the Project to participate in Service Offering';
  end if;
  return NEW;
end;
$$ language plpgsql;
revoke all on function public.enforce_offering_company_project_match() from public, anon;

drop trigger if exists trg_offering_company_project_check on public.service_offering_companies;
create trigger trg_offering_company_project_check
before insert on public.service_offering_companies
for each row execute function public.enforce_offering_company_project_match();

-- 4. Company RBAC Tables

-- 4.1 Company Roles
create table if not exists public.company_roles (
  id uuid default gen_random_uuid() primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  company_id uuid not null,
  name text not null,
  created_at timestamptz default now(),
  unique(company_id, name),
  unique(id, tenant_id), -- For Composite FK
  foreign key (company_id, tenant_id) references public.companies(id, tenant_id) on delete cascade
);
alter table public.company_roles enable row level security;
alter table public.company_roles force row level security;

-- 4.2 Company Users
create table if not exists public.company_users (
  company_id uuid,
  user_id uuid references auth.users(id) on delete cascade,
  role_id uuid not null,
  tenant_id uuid not null,
  primary key (company_id, user_id),
  foreign key (company_id, tenant_id) references public.companies(id, tenant_id) on delete cascade,
  foreign key (role_id, tenant_id) references public.company_roles(id, tenant_id) -- Strict Role Scope Match
);
alter table public.company_users enable row level security;
alter table public.company_users force row level security;

-- 4.3 Company Role Permissions
create table if not exists public.company_role_permissions (
  role_id uuid references public.company_roles(id) on delete cascade,
  permission_id uuid references public.permissions(id) on delete cascade,
  primary key (role_id, permission_id)
);
alter table public.company_role_permissions enable row level security;
alter table public.company_role_permissions force row level security;

-- Trigger: Ensure permission has scope='company' (SECURITY DEFINER)
create or replace function public.enforce_company_perm_scope() returns trigger 
security definer
set search_path = public, extensions, auth
as $$
begin
  if (select scope from public.permissions where id = NEW.permission_id) != 'company' then
    raise exception 'Company roles can only have company-scoped permissions';
  end if;
  return NEW;
end;
$$ language plpgsql;
revoke all on function public.enforce_company_perm_scope() from public, anon;

drop trigger if exists trg_company_role_perm_scope on public.company_role_permissions;
create trigger trg_company_role_perm_scope
before insert on public.company_role_permissions
for each row execute function public.enforce_company_perm_scope();

-- 5. RLS Policies (Consolidated) – SELECT ONLY

-- 5.1 Groups
drop policy if exists "groups_select" on public.groups;
create policy "groups_select" on public.groups for select to authenticated
using (
  exists (
    select 1 from public.group_members gm
    where gm.group_id = groups.id
    and gm.user_id = auth.uid()
    and gm.tenant_id = groups.tenant_id -- Tenant Match
  )
);
revoke insert, update, delete on public.groups from authenticated;

-- 5.2 Group Members
drop policy if exists "group_members_select" on public.group_members;
create policy "group_members_select" on public.group_members for select to authenticated
using (
  (user_id = auth.uid()) 
  or exists (
    select 1 from public.group_members gm
    where gm.group_id = group_members.group_id
    and gm.user_id = auth.uid()
    and gm.tenant_id = group_members.tenant_id -- Tenant Match
  )
);
revoke insert, update, delete on public.group_members from authenticated;

-- 5.3 Organizations
drop policy if exists "org_select" on public.organizations;
create policy "org_select" on public.organizations for select to authenticated
using ( 
  -- Path 1: Owner Group Member
  exists (
    select 1 from public.group_members gm
    where gm.group_id = organizations.owner_group_id
    and gm.user_id = auth.uid()
    and gm.tenant_id = organizations.tenant_id -- Tenant Match
  )
  -- Path 2: Member of Linked Company
  or exists (
    select 1 from public.org_companies oc
    join public.company_users cu on cu.company_id = oc.company_id
    where oc.organization_id = organizations.id
    and cu.user_id = auth.uid()
    and oc.tenant_id = organizations.tenant_id -- Tenant Match
    and cu.tenant_id = organizations.tenant_id -- Tenant Match
  )
);
revoke insert, update, delete on public.organizations from authenticated;

-- 5.4 Companies
drop policy if exists "company_select" on public.companies;
create policy "company_select" on public.companies for select to authenticated
using (
  -- Path 1: Direct Member
  exists (
    select 1 from public.company_users cu
    where cu.company_id = companies.id 
    and cu.user_id = auth.uid()
    and cu.tenant_id = companies.tenant_id -- Tenant Match
  )
  -- Path 2: Parent Org Owner
  or exists (
    select 1 from public.org_companies oc
    join public.organizations o on o.id = oc.organization_id
    join public.group_members gm on gm.group_id = o.owner_group_id
    where oc.company_id = companies.id
    and gm.user_id = auth.uid()
    and oc.tenant_id = companies.tenant_id     -- Tenant Match
    and o.tenant_id = companies.tenant_id      -- Tenant Match
    and gm.tenant_id = companies.tenant_id     -- Tenant Match
  )
);
revoke insert, update, delete on public.companies from authenticated;

-- 5.5 Projects
drop policy if exists "project_select" on public.projects;
create policy "project_select" on public.projects for select to authenticated
using (
   -- Path 1: Direct Company Member on Project
   exists (
     select 1 from public.project_companies pc
     join public.company_users cu on cu.company_id = pc.company_id
     where pc.project_id = projects.id
     and cu.user_id = auth.uid()
     and pc.tenant_id = projects.tenant_id
     and cu.tenant_id = projects.tenant_id
   )
   -- Path 2: Org Owner
   or exists (
     select 1 from public.organizations o
     join public.group_members gm on gm.group_id = o.owner_group_id
     where o.id = projects.organization_id
     and gm.user_id = auth.uid()
     and o.tenant_id = projects.tenant_id
     and gm.tenant_id = projects.tenant_id
   )
);
revoke insert, update, delete on public.projects from authenticated;

-- 5.6 Service Offerings
drop policy if exists "service_offering_select" on public.service_offerings;
create policy "service_offering_select" on public.service_offerings for select to authenticated
using (
     -- Path 1: Owner Group Member
    exists (
      select 1 from public.group_members gm
      where gm.group_id = service_offerings.owner_group_id
      and gm.user_id = auth.uid()
      and gm.tenant_id = service_offerings.tenant_id
    )
    -- Path 2: Project Member via Company (Implicitly visible if Project is visible? No, let's keep it strict.)
    -- Constraint: "Visible if Project visible" 
    or exists (
       select 1 from public.projects p
       where p.id = service_offerings.project_id
       and p.tenant_id = service_offerings.tenant_id
       and (
          -- Project Logic: Company Member
          exists (
             select 1 from public.project_companies pc
             join public.company_users cu on cu.company_id = pc.company_id
             where pc.project_id = p.id
             and cu.user_id = auth.uid()
             and pc.tenant_id = p.tenant_id
             and cu.tenant_id = p.tenant_id
          )
          -- Project Logic: Org Owner
          or exists (
             select 1 from public.organizations o
             join public.group_members gm on gm.group_id = o.owner_group_id
             where o.id = p.organization_id
             and gm.user_id = auth.uid()
             and o.tenant_id = p.tenant_id
             and gm.tenant_id = p.tenant_id
          )
       )
    )
);
revoke insert, update, delete on public.service_offerings from authenticated;

-- 5.7 Link Tables (Revoke All Writes)
revoke insert, update, delete on public.org_companies from authenticated;
revoke insert, update, delete on public.project_companies from authenticated;
revoke insert, update, delete on public.service_offering_companies from authenticated;

-- 5.8 Company RBAC (Revoke All Writes)
revoke insert, update, delete on public.company_roles from authenticated;
revoke insert, update, delete on public.company_users from authenticated;
revoke insert, update, delete on public.company_role_permissions from authenticated;

-- RLS for Company RBAC
drop policy if exists "company_users_select" on public.company_users;
create policy "company_users_select" on public.company_users for select to authenticated
using (
  (user_id = auth.uid())
  or exists (
    -- Visible to members of the same company
    select 1 from public.company_users cu
    where cu.company_id = company_users.company_id
    and cu.user_id = auth.uid()
    and cu.tenant_id = company_users.tenant_id
  )
);

drop policy if exists "company_roles_select" on public.company_roles;
create policy "company_roles_select" on public.company_roles for select to authenticated
using (
  exists (
    select 1 from public.company_users cu
    where cu.company_id = company_roles.company_id
    and cu.user_id = auth.uid()
    and cu.tenant_id = company_roles.tenant_id
  )
);

drop policy if exists "company_role_perms_select" on public.company_role_permissions;
create policy "company_role_perms_select" on public.company_role_permissions for select to authenticated
using (
  exists (
    select 1 from public.company_roles cr
    join public.company_users cu on cu.company_id = cr.company_id
    where cr.id = company_role_permissions.role_id
    and cu.user_id = auth.uid()
    and cu.tenant_id = cr.tenant_id -- Implicit tenant join via roles
  )
);

-- Part 2: Business Hierarchy RPC Suite
-- ------------------------------------------------------------------------------
-- Helper: Verify Tenant Membership
create or replace function public.verify_tenant_membership(p_tenant_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
begin
  if not exists (
    select 1 from public.tenant_users 
    where tenant_id = p_tenant_id 
    and user_id = auth.uid()
  ) then
    raise exception 'Access Denied: User is not a member of this tenant';
  end if;
end;
$$ language plpgsql;
revoke all on function public.verify_tenant_membership(uuid) from public, anon;
grant execute on function public.verify_tenant_membership(uuid) to authenticated;

-- Groups RPCs
create or replace function public.create_group(p_tenant_id uuid, p_name text) returns uuid
security definer set search_path = public, extensions, auth
as $$
declare
  v_group_id uuid;
begin
  perform public.verify_tenant_membership(p_tenant_id);
  
  insert into public.groups (tenant_id, name)
  values (p_tenant_id, p_name)
  returning id into v_group_id;
  
  -- Auto-add creator as member
  insert into public.group_members (group_id, user_id, tenant_id)
  values (v_group_id, auth.uid(), p_tenant_id);
  
  return v_group_id;
end;
$$ language plpgsql;
revoke all on function public.create_group(uuid, text) from public, anon;
grant execute on function public.create_group(uuid, text) to authenticated;

create or replace function public.rename_group(p_tenant_id uuid, p_group_id uuid, p_name text) returns void
security definer set search_path = public, extensions, auth
as $$
begin
  -- Check membership
  if not exists (
    select 1 from public.group_members 
    where group_id = p_group_id and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be a group member to rename';
  end if;

  update public.groups set name = p_name, updated_at = now()
  where id = p_group_id and tenant_id = p_tenant_id;
end;
$$ language plpgsql;
revoke all on function public.rename_group(uuid, uuid, text) from public, anon;
grant execute on function public.rename_group(uuid, uuid, text) to authenticated;

create or replace function public.delete_group(p_tenant_id uuid, p_group_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
begin
  -- Check membership (Strictly, maybe need admin? For now, member is owner-ish)
  if not exists (
    select 1 from public.group_members 
    where group_id = p_group_id and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be a group member to delete';
  end if;

  delete from public.groups where id = p_group_id and tenant_id = p_tenant_id;
end;
$$ language plpgsql;
revoke all on function public.delete_group(uuid, uuid) from public, anon;
grant execute on function public.delete_group(uuid, uuid) to authenticated;

create or replace function public.add_group_member(p_tenant_id uuid, p_group_id uuid, p_user_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
begin
  -- Check invoker membership
  if not exists (
    select 1 from public.group_members 
    where group_id = p_group_id and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be a group member to add others';
  end if;
  
  -- Ensure target user is in tenant
  if not exists (
    select 1 from public.tenant_users
    where tenant_id = p_tenant_id and user_id = p_user_id
  ) then
    raise exception 'Target user not in tenant';
  end if;

  insert into public.group_members (group_id, user_id, tenant_id)
  values (p_group_id, p_user_id, p_tenant_id)
  on conflict do nothing;
end;
$$ language plpgsql;
revoke all on function public.add_group_member(uuid, uuid, uuid) from public, anon;
grant execute on function public.add_group_member(uuid, uuid, uuid) to authenticated;

create or replace function public.remove_group_member(p_tenant_id uuid, p_group_id uuid, p_user_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
begin
  -- Check invoker membership
  if not exists (
    select 1 from public.group_members 
    where group_id = p_group_id and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be a group member to remove others';
  end if;

  delete from public.group_members 
  where group_id = p_group_id and user_id = p_user_id and tenant_id = p_tenant_id;
end;
$$ language plpgsql;
revoke all on function public.remove_group_member(uuid, uuid, uuid) from public, anon;
grant execute on function public.remove_group_member(uuid, uuid, uuid) to authenticated;
-- Organizations RPCs

create or replace function public.create_organization(p_tenant_id uuid, p_name text, p_owner_group_id uuid) returns uuid
security definer set search_path = public, extensions, auth
as $$
declare
  v_org_id uuid;
begin
  perform public.verify_tenant_membership(p_tenant_id);
  
  -- Must be member of owner group
  if not exists (
    select 1 from public.group_members 
    where group_id = p_owner_group_id and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be member of owner group';
  end if;

  insert into public.organizations (tenant_id, name, owner_group_id)
  values (p_tenant_id, p_name, p_owner_group_id)
  returning id into v_org_id;
  
  return v_org_id;
end;
$$ language plpgsql;
revoke all on function public.create_organization(uuid, text, uuid) from public, anon;
grant execute on function public.create_organization(uuid, text, uuid) to authenticated;

create or replace function public.update_organization(p_tenant_id uuid, p_org_id uuid, p_name text, p_owner_group_id uuid default null) returns void
security definer set search_path = public, extensions, auth
as $$
declare
  v_current_owner_group_id uuid;
begin
  select owner_group_id into v_current_owner_group_id from public.organizations where id = p_org_id and tenant_id = p_tenant_id;
  
  -- Must be member of current owner group
  if not exists (
    select 1 from public.group_members 
    where group_id = v_current_owner_group_id and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be member of owner group';
  end if;

  if p_owner_group_id is not null then
     -- Validate new group is in tenant
    if not exists (select 1 from public.groups where id = p_owner_group_id and tenant_id = p_tenant_id) then
        raise exception 'New owner group invalid';
    end if;
  end if;

  update public.organizations 
  set name = coalesce(p_name, name),
      owner_group_id = coalesce(p_owner_group_id, owner_group_id),
      updated_at = now()
  where id = p_org_id and tenant_id = p_tenant_id;
end;
$$ language plpgsql;
revoke all on function public.update_organization(uuid, uuid, text, uuid) from public, anon;
grant execute on function public.update_organization(uuid, uuid, text, uuid) to authenticated;

create or replace function public.delete_organization(p_tenant_id uuid, p_org_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
declare
  v_owner_group_id uuid;
begin
  select owner_group_id into v_owner_group_id from public.organizations where id = p_org_id and tenant_id = p_tenant_id;
  
  if not exists (
    select 1 from public.group_members 
    where group_id = v_owner_group_id and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be member of owner group';
  end if;

  delete from public.organizations where id = p_org_id and tenant_id = p_tenant_id;
end;
$$ language plpgsql;
revoke all on function public.delete_organization(uuid, uuid) from public, anon;
grant execute on function public.delete_organization(uuid, uuid) to authenticated;

create or replace function public.link_company_to_org(p_tenant_id uuid, p_org_id uuid, p_company_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
declare
  v_owner_group_id uuid;
begin
  select owner_group_id into v_owner_group_id from public.organizations where id = p_org_id and tenant_id = p_tenant_id;
  
  if not exists (
    select 1 from public.group_members 
    where group_id = v_owner_group_id and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be member of owner group';
  end if;
  
  -- Company must be in same tenant
  if not exists (select 1 from public.companies where id = p_company_id and tenant_id = p_tenant_id) then
    raise exception 'Company not found in tenant';
  end if;

  insert into public.org_companies (organization_id, company_id, tenant_id)
  values (p_org_id, p_company_id, p_tenant_id)
  on conflict do nothing;
end;
$$ language plpgsql;
revoke all on function public.link_company_to_org(uuid, uuid, uuid) from public, anon;
grant execute on function public.link_company_to_org(uuid, uuid, uuid) to authenticated;


create or replace function public.unlink_company_from_org(p_tenant_id uuid, p_org_id uuid, p_company_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
declare
  v_owner_group_id uuid;
begin
  select owner_group_id into v_owner_group_id from public.organizations where id = p_org_id and tenant_id = p_tenant_id;
  
  if not exists (
    select 1 from public.group_members 
    where group_id = v_owner_group_id and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be member of owner group';
  end if;

  delete from public.org_companies 
  where organization_id = p_org_id and company_id = p_company_id and tenant_id = p_tenant_id;
end;
$$ language plpgsql;
revoke all on function public.unlink_company_from_org(uuid, uuid, uuid) from public, anon;
grant execute on function public.unlink_company_from_org(uuid, uuid, uuid) to authenticated;

-- Companies RPCs

create or replace function public.create_company(p_tenant_id uuid, p_name text) returns uuid
security definer set search_path = public, extensions, auth
as $$
declare
  v_company_id uuid;
begin
  perform public.verify_tenant_membership(p_tenant_id);
  
  insert into public.companies (tenant_id, name)
  values (p_tenant_id, p_name)
  returning id into v_company_id;
  
  -- Auto-add creator as Admin? Requires Role. 
  -- For now, we just create the company. Caller must add themselves via add_company_member (which requires admin... bootstrap problem?)
  -- Bootstrap: Add creator as 'admin' role.
  
  -- 1. Create 'Admin' Role for this company
  insert into public.company_roles (tenant_id, company_id, name)
  values (p_tenant_id, v_company_id, 'Admin');
  
  -- 2. Add User
  insert into public.company_users (company_id, user_id, role_id, tenant_id)
  select v_company_id, auth.uid(), id, p_tenant_id
  from public.company_roles 
  where company_id = v_company_id and name = 'Admin';

  return v_company_id;
end;
$$ language plpgsql;
revoke all on function public.create_company(uuid, text) from public, anon;
grant execute on function public.create_company(uuid, text) to authenticated;

create or replace function public.update_company(p_tenant_id uuid, p_company_id uuid, p_name text) returns void
security definer set search_path = public, extensions, auth
as $$
begin
  -- Check Company Admin
  if not exists (
    select 1 from public.company_users cu
    join public.company_roles cr on cr.id = cu.role_id
    where cu.company_id = p_company_id 
    and cu.user_id = auth.uid() 
    and cu.tenant_id = p_tenant_id
    and cr.name = 'Admin' -- Hardcoded check for now, ideally explicit permission
  ) then
    raise exception 'Access Denied: Must be Company Admin';
  end if;

  update public.companies set name = p_name, updated_at = now()
  where id = p_company_id and tenant_id = p_tenant_id;
end;
$$ language plpgsql;
revoke all on function public.update_company(uuid, uuid, text) from public, anon;
grant execute on function public.update_company(uuid, uuid, text) to authenticated;

create or replace function public.delete_company(p_tenant_id uuid, p_company_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
begin
   -- Check Company Admin
  if not exists (
    select 1 from public.company_users cu
    join public.company_roles cr on cr.id = cu.role_id
    where cu.company_id = p_company_id 
    and cu.user_id = auth.uid() 
    and cu.tenant_id = p_tenant_id
    and cr.name = 'Admin'
  ) then
    raise exception 'Access Denied: Must be Company Admin';
  end if;

  delete from public.companies where id = p_company_id and tenant_id = p_tenant_id;
end;
$$ language plpgsql;
revoke all on function public.delete_company(uuid, uuid) from public, anon;
grant execute on function public.delete_company(uuid, uuid) to authenticated;
-- Projects RPCs

create or replace function public.create_project(p_tenant_id uuid, p_organization_id uuid, p_name text) returns uuid
security definer set search_path = public, extensions, auth
as $$
declare
  v_project_id uuid;
  v_org_owner_group uuid;
begin
  -- Check Org Ownership
  select owner_group_id into v_org_owner_group from public.organizations where id = p_organization_id and tenant_id = p_tenant_id;
  
  if not exists (
    select 1 from public.group_members 
    where group_id = v_org_owner_group and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be Org Owner to create Project';
  end if;

  insert into public.projects (tenant_id, organization_id, name)
  values (p_tenant_id, p_organization_id, p_name)
  returning id into v_project_id;
  
  return v_project_id;
end;
$$ language plpgsql;
revoke all on function public.create_project(uuid, uuid, text) from public, anon;
grant execute on function public.create_project(uuid, uuid, text) to authenticated;

create or replace function public.link_company_to_project(p_tenant_id uuid, p_project_id uuid, p_company_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
declare
    v_org_owner_group uuid;
    v_org_id uuid;
begin
  select organization_id into v_org_id from public.projects where id = p_project_id and tenant_id = p_tenant_id;
  select owner_group_id into v_org_owner_group from public.organizations where id = v_org_id and tenant_id = p_tenant_id;

   if not exists (
    select 1 from public.group_members 
    where group_id = v_org_owner_group and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be Org Owner to manage Project Links';
  end if;

  insert into public.project_companies (project_id, company_id, tenant_id)
  values (p_project_id, p_company_id, p_tenant_id)
  on conflict do nothing;
end;
$$ language plpgsql;
revoke all on function public.link_company_to_project(uuid, uuid, uuid) from public, anon;
grant execute on function public.link_company_to_project(uuid, uuid, uuid) to authenticated;

-- Service Offerings RPCs (Abbreviated, following pattern)

create or replace function public.create_service_offering(p_tenant_id uuid, p_project_id uuid, p_name text, p_owner_group_id uuid) returns uuid
security definer set search_path = public, extensions, auth
as $$
declare
  v_id uuid;
begin
  perform public.verify_tenant_membership(p_tenant_id);
  -- Check Member of owner group
   if not exists (
    select 1 from public.group_members 
    where group_id = p_owner_group_id and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be member of owner group';
  end if;

  insert into public.service_offerings (tenant_id, project_id, name, owner_group_id)
  values (p_tenant_id, p_project_id, p_name, p_owner_group_id)
  returning id into v_id;
  return v_id;
end;
$$ language plpgsql;
revoke all on function public.create_service_offering(uuid, uuid, text, uuid) from public, anon;
grant execute on function public.create_service_offering(uuid, uuid, text, uuid) to authenticated;


create or replace function public.update_project(p_tenant_id uuid, p_project_id uuid, p_name text) returns void
security definer set search_path = public, extensions, auth
as $$
declare
  v_org_id uuid;
  v_org_owner_group uuid;
begin
  select organization_id into v_org_id from public.projects where id = p_project_id and tenant_id = p_tenant_id;
  select owner_group_id into v_org_owner_group from public.organizations where id = v_org_id and tenant_id = p_tenant_id;
  
  if not exists (
    select 1 from public.group_members 
    where group_id = v_org_owner_group and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be Org Owner to update Project';
  end if;

  update public.projects set name = p_name, updated_at = now()
  where id = p_project_id and tenant_id = p_tenant_id;
end;
$$ language plpgsql;
revoke all on function public.update_project(uuid, uuid, text) from public, anon;
grant execute on function public.update_project(uuid, uuid, text) to authenticated;

create or replace function public.delete_project(p_tenant_id uuid, p_project_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
declare
  v_org_id uuid;
  v_org_owner_group uuid;
begin
  select organization_id into v_org_id from public.projects where id = p_project_id and tenant_id = p_tenant_id;
  select owner_group_id into v_org_owner_group from public.organizations where id = v_org_id and tenant_id = p_tenant_id;
  
  if not exists (
    select 1 from public.group_members 
    where group_id = v_org_owner_group and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be Org Owner to delete Project';
  end if;

  delete from public.projects where id = p_project_id and tenant_id = p_tenant_id;
end;
$$ language plpgsql;
revoke all on function public.delete_project(uuid, uuid) from public, anon;
grant execute on function public.delete_project(uuid, uuid) to authenticated;

create or replace function public.unlink_company_from_project(p_tenant_id uuid, p_project_id uuid, p_company_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
declare
  v_org_id uuid;
  v_org_owner_group uuid;
begin
  select organization_id into v_org_id from public.projects where id = p_project_id and tenant_id = p_tenant_id;
  select owner_group_id into v_org_owner_group from public.organizations where id = v_org_id and tenant_id = p_tenant_id;
  
  if not exists (
    select 1 from public.group_members 
    where group_id = v_org_owner_group and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be Org Owner to unlink company';
  end if;

  delete from public.project_companies 
  where project_id = p_project_id and company_id = p_company_id and tenant_id = p_tenant_id;
end;
$$ language plpgsql;
revoke all on function public.unlink_company_from_project(uuid, uuid, uuid) from public, anon;
grant execute on function public.unlink_company_from_project(uuid, uuid, uuid) to authenticated;

create or replace function public.update_service_offering(p_tenant_id uuid, p_offering_id uuid, p_name text, p_owner_group_id uuid default null) returns void
security definer set search_path = public, extensions, auth
as $$
declare
  v_current_owner_group_id uuid;
begin
  select owner_group_id into v_current_owner_group_id from public.service_offerings where id = p_offering_id and tenant_id = p_tenant_id;
  
  if not exists (
    select 1 from public.group_members 
    where group_id = v_current_owner_group_id and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be member of owner group';
  end if;
  
  if p_owner_group_id is not null then
      if not exists (select 1 from public.groups where id = p_owner_group_id and tenant_id = p_tenant_id) then
        raise exception 'New owner group invalid';
      end if;
  end if;

  update public.service_offerings 
  set name = coalesce(p_name, name),
      owner_group_id = coalesce(p_owner_group_id, owner_group_id),
      updated_at = now()
  where id = p_offering_id and tenant_id = p_tenant_id;
end;
$$ language plpgsql;
revoke all on function public.update_service_offering(uuid, uuid, text, uuid) from public, anon;
grant execute on function public.update_service_offering(uuid, uuid, text, uuid) to authenticated;

create or replace function public.delete_service_offering(p_tenant_id uuid, p_offering_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
declare
  v_owner_group_id uuid;
begin
  select owner_group_id into v_owner_group_id from public.service_offerings where id = p_offering_id and tenant_id = p_tenant_id;
  
  if not exists (
    select 1 from public.group_members 
    where group_id = v_owner_group_id and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be member of owner group';
  end if;

  delete from public.service_offerings where id = p_offering_id and tenant_id = p_tenant_id;
end;
$$ language plpgsql;
revoke all on function public.delete_service_offering(uuid, uuid) from public, anon;
grant execute on function public.delete_service_offering(uuid, uuid) to authenticated;

create or replace function public.link_company_to_service_offering(p_tenant_id uuid, p_offering_id uuid, p_company_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
declare
  v_owner_group_id uuid;
begin
  select owner_group_id into v_owner_group_id from public.service_offerings where id = p_offering_id and tenant_id = p_tenant_id;
  
  if not exists (
    select 1 from public.group_members 
    where group_id = v_owner_group_id and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be member of owner group';
  end if;
  
  -- Company must be in tenant (and project, enforced by trigger)
  insert into public.service_offering_companies (service_offering_id, company_id, tenant_id)
  values (p_offering_id, p_company_id, p_tenant_id)
  on conflict do nothing;
end;
$$ language plpgsql;
revoke all on function public.link_company_to_service_offering(uuid, uuid, uuid) from public, anon;
grant execute on function public.link_company_to_service_offering(uuid, uuid, uuid) to authenticated;

create or replace function public.unlink_company_from_service_offering(p_tenant_id uuid, p_offering_id uuid, p_company_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
declare
  v_owner_group_id uuid;
begin
  select owner_group_id into v_owner_group_id from public.service_offerings where id = p_offering_id and tenant_id = p_tenant_id;
  
  if not exists (
    select 1 from public.group_members 
    where group_id = v_owner_group_id and user_id = auth.uid() and tenant_id = p_tenant_id
  ) then
    raise exception 'Access Denied: Must be member of owner group';
  end if;

  delete from public.service_offering_companies 
  where service_offering_id = p_offering_id and company_id = p_company_id and tenant_id = p_tenant_id;
end;
$$ language plpgsql;
revoke all on function public.unlink_company_from_service_offering(uuid, uuid, uuid) from public, anon;
grant execute on function public.unlink_company_from_service_offering(uuid, uuid, uuid) to authenticated;
-- Company RBAC RPCs (from file 03)

create or replace function public.create_company_role(p_tenant_id uuid, p_company_id uuid, p_name text) returns uuid
security definer set search_path = public, extensions, auth
as $$
declare
  v_role_id uuid;
begin
  -- Check Company Admin (Hardcoded role name 'Admin' for now, or check explicit permission)
  if not exists (
    select 1 from public.company_users cu
    join public.company_roles cr on cr.id = cu.role_id
    where cu.company_id = p_company_id 
    and cu.user_id = auth.uid() 
    and cu.tenant_id = p_tenant_id
    and cr.name = 'Admin'
  ) then
    raise exception 'Access Denied: Must be Company Admin';
  end if;

  insert into public.company_roles (tenant_id, company_id, name)
  values (p_tenant_id, p_company_id, p_name)
  returning id into v_role_id;
  
  return v_role_id;
end;
$$ language plpgsql;
revoke all on function public.create_company_role(uuid, uuid, text) from public, anon;
grant execute on function public.create_company_role(uuid, uuid, text) to authenticated;

create or replace function public.delete_company_role(p_tenant_id uuid, p_company_id uuid, p_role_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
begin
  -- Check Company Admin
  if not exists (
    select 1 from public.company_users cu
    join public.company_roles cr on cr.id = cu.role_id
    where cu.company_id = p_company_id 
    and cu.user_id = auth.uid() 
    and cu.tenant_id = p_tenant_id
    and cr.name = 'Admin'
  ) then
    raise exception 'Access Denied: Must be Company Admin';
  end if;

  delete from public.company_roles where id = p_role_id and company_id = p_company_id and tenant_id = p_tenant_id;
end;
$$ language plpgsql;
revoke all on function public.delete_company_role(uuid, uuid, uuid) from public, anon;
grant execute on function public.delete_company_role(uuid, uuid, uuid) to authenticated;

create or replace function public.add_company_user(p_tenant_id uuid, p_company_id uuid, p_user_id uuid, p_role_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
begin
  -- Check Company Admin
  if not exists (
    select 1 from public.company_users cu
    join public.company_roles cr on cr.id = cu.role_id
    where cu.company_id = p_company_id 
    and cu.user_id = auth.uid() 
    and cu.tenant_id = p_tenant_id
    and cr.name = 'Admin'
  ) then
    raise exception 'Access Denied: Must be Company Admin';
  end if;
  
  -- Verify User in Tenant
  if not exists (select 1 from public.tenant_users where tenant_id = p_tenant_id and user_id = p_user_id) then
     raise exception 'User not in tenant';
  end if;

  -- Verify Role belongs to Company
  if not exists (select 1 from public.company_roles where id = p_role_id and company_id = p_company_id and tenant_id = p_tenant_id) then
     raise exception 'Role does not belong to company';
  end if;

  insert into public.company_users (company_id, user_id, role_id, tenant_id)
  values (p_company_id, p_user_id, p_role_id, p_tenant_id)
  on conflict do nothing;
end;
$$ language plpgsql;
revoke all on function public.add_company_user(uuid, uuid, uuid, uuid) from public, anon;
grant execute on function public.add_company_user(uuid, uuid, uuid, uuid) to authenticated;

create or replace function public.remove_company_user(p_tenant_id uuid, p_company_id uuid, p_user_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
begin
  -- Check Company Admin
  if not exists (
    select 1 from public.company_users cu
    join public.company_roles cr on cr.id = cu.role_id
    where cu.company_id = p_company_id 
    and cu.user_id = auth.uid() 
    and cu.tenant_id = p_tenant_id
    and cr.name = 'Admin'
  ) then
    raise exception 'Access Denied: Must be Company Admin';
  end if;

  delete from public.company_users 
  where company_id = p_company_id and user_id = p_user_id and tenant_id = p_tenant_id;
end;
$$ language plpgsql;
revoke all on function public.remove_company_user(uuid, uuid, uuid) from public, anon;
grant execute on function public.remove_company_user(uuid, uuid, uuid) to authenticated;

create or replace function public.grant_company_permission(p_tenant_id uuid, p_role_id uuid, p_permission_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
declare
  v_company_id uuid;
begin
  -- Resolve company from role
  select company_id into v_company_id from public.company_roles where id = p_role_id and tenant_id = p_tenant_id;
  
  if v_company_id is null then
     raise exception 'Role not found';
  end if;

  -- Check Company Admin
  if not exists (
    select 1 from public.company_users cu
    join public.company_roles cr on cr.id = cu.role_id
    where cu.company_id = v_company_id 
    and cu.user_id = auth.uid() 
    and cu.tenant_id = p_tenant_id
    and cr.name = 'Admin'
  ) then
    raise exception 'Access Denied: Must be Company Admin';
  end if;
  
  -- Verify permission scope is company (trigger handles this, but good to check early)
  if (select scope from public.permissions where id = p_permission_id) != 'company' then
     raise exception 'Permission scope mismatch';
  end if;

  insert into public.company_role_permissions (role_id, permission_id)
  values (p_role_id, p_permission_id)
  on conflict do nothing;
end;
$$ language plpgsql;
revoke all on function public.grant_company_permission(uuid, uuid, uuid) from public, anon;
grant execute on function public.grant_company_permission(uuid, uuid, uuid) to authenticated;

create or replace function public.revoke_company_permission(p_tenant_id uuid, p_role_id uuid, p_permission_id uuid) returns void
security definer set search_path = public, extensions, auth
as $$
declare
  v_company_id uuid;
begin
  -- Resolve company from role
  select company_id into v_company_id from public.company_roles where id = p_role_id and tenant_id = p_tenant_id;
  
  if v_company_id is null then
     raise exception 'Role not found';
  end if;

  -- Check Company Admin
  if not exists (
    select 1 from public.company_users cu
    join public.company_roles cr on cr.id = cu.role_id
    where cu.company_id = v_company_id 
    and cu.user_id = auth.uid() 
    and cu.tenant_id = p_tenant_id
    and cr.name = 'Admin'
  ) then
    raise exception 'Access Denied: Must be Company Admin';
  end if;

  delete from public.company_role_permissions 
  where role_id = p_role_id and permission_id = p_permission_id;
end;
$$ language plpgsql;
revoke all on function public.revoke_company_permission(uuid, uuid, uuid) from public, anon;
grant execute on function public.revoke_company_permission(uuid, uuid, uuid) to authenticated;
-- Part 3: Edit Locks
-- ------------------------------------------------------------------------------
create table if not exists public.edit_locks (
    tenant_id uuid not null references public.tenants(id) on delete cascade,
    entity_type text not null,
    entity_id uuid not null,
    locked_by uuid not null references auth.users(id) on delete cascade,
    locked_at timestamptz not null default now(),
    expires_at timestamptz not null,
    primary key (tenant_id, entity_type, entity_id)
);
create index if not exists idx_edit_locks_tenant_id on public.edit_locks(tenant_id);
create index if not exists idx_edit_locks_expires_at on public.edit_locks(expires_at);

alter table public.edit_locks enable row level security;
alter table public.edit_locks force row level security;

drop policy if exists "Users can view locks in their tenant" on public.edit_locks;
create policy "Users can view locks in their tenant"
    on public.edit_locks for select to authenticated
    using (
        exists (
            select 1 from public.tenant_users
            where tenant_users.tenant_id = edit_locks.tenant_id
            and tenant_users.user_id = auth.uid()
        )
    );
revoke all on public.edit_locks from public, anon;
grant select on public.edit_locks to authenticated;

-- RPC: acquire_edit_lock
create or replace function public.acquire_edit_lock(
    p_tenant_id uuid,
    p_entity_type text,
    p_entity_id uuid,
    p_override boolean default false,
    p_ttl_seconds int default 600
)
returns table(success boolean, locked_by uuid, expires_at timestamptz)
language plpgsql security definer set search_path = public, extensions, auth
as $$
declare
    v_user_id uuid;
    v_existing_lock record;
    v_new_expiry timestamptz;
begin
    v_user_id := auth.uid();
    if p_ttl_seconds is null or p_ttl_seconds < 30 or p_ttl_seconds > 3600 then
        raise exception 'Invalid ttl_seconds: Must be between 30 and 3600';
    end if;
    if not exists (select 1 from public.tenant_users where tenant_id = p_tenant_id and user_id = v_user_id) then
        raise exception 'Access Denied: User not member of tenant';
    end if;

    v_new_expiry := now() + (p_ttl_seconds || ' seconds')::interval;

    insert into public.edit_locks (tenant_id, entity_type, entity_id, locked_by, expires_at)
    values (p_tenant_id, p_entity_type, p_entity_id, v_user_id, v_new_expiry)
    on conflict (tenant_id, entity_type, entity_id)
    do update
    set 
        locked_by = case 
                when edit_locks.expires_at < now() then v_user_id
                when edit_locks.locked_by = v_user_id then v_user_id
                when p_override = true then v_user_id
                else edit_locks.locked_by
            end,
        expires_at = case
                when edit_locks.expires_at < now() or edit_locks.locked_by = v_user_id or p_override = true 
                then v_new_expiry
                else edit_locks.expires_at
            end,
        locked_at = case
                when edit_locks.expires_at < now() or edit_locks.locked_by = v_user_id or p_override = true 
                then now()
                else edit_locks.locked_at
            end
    returning locked_by, expires_at into v_existing_lock;

    if v_existing_lock.locked_by = v_user_id then
        return query select true, v_existing_lock.locked_by, v_existing_lock.expires_at;
    else
        return query select false, v_existing_lock.locked_by, v_existing_lock.expires_at;
    end if;
end;
$$;
revoke all on function public.acquire_edit_lock from public, anon;
grant execute on function public.acquire_edit_lock to authenticated;

-- RPC: release_edit_lock
create or replace function public.release_edit_lock(p_tenant_id uuid, p_entity_type text, p_entity_id uuid)
returns boolean
language plpgsql security definer set search_path = public, extensions, auth
as $$
declare v_user_id uuid;
begin
    v_user_id := auth.uid();
    delete from public.edit_locks
    where tenant_id = p_tenant_id and entity_type = p_entity_type and entity_id = p_entity_id and locked_by = v_user_id;
    return found;
end;
$$;
revoke all on function public.release_edit_lock from public, anon;
grant execute on function public.release_edit_lock to authenticated;
-- Part 4: 2FA Login Challenges and Sessions (STRICT)
-- ------------------------------------------------------------------------------
-- 1. Create login_challenges table
CREATE TABLE if not exists public.login_challenges (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    user_id uuid NOT NULL,
    code_hash text NOT NULL,
    created_at timestamptz DEFAULT now(),
    expires_at timestamptz NOT NULL,
    verified_at timestamptz,
    CONSTRAINT login_challenges_pkey PRIMARY KEY (id),
    CONSTRAINT login_challenges_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE,
    CONSTRAINT login_challenges_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE INDEX if not exists idx_login_challenges_lookup ON public.login_challenges(tenant_id, user_id, created_at DESC);
CREATE INDEX if not exists idx_login_challenges_expires ON public.login_challenges(expires_at);

ALTER TABLE public.login_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_challenges FORCE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.login_challenges FROM public, anon, authenticated;
-- Allow Select to authenticated (debug/audit) but limited by policy
GRANT SELECT ON TABLE public.login_challenges TO authenticated;

drop policy if exists "Users can see own challenges" on public.login_challenges;
CREATE POLICY "Users can see own challenges" ON public.login_challenges
    FOR SELECT TO authenticated USING (user_id = auth.uid());

-- 2. Create twofa_sessions table
CREATE TABLE if not exists public.twofa_sessions (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    tenant_slug text NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamptz DEFAULT now(),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    last_rotated_at timestamptz DEFAULT now(),
    CONSTRAINT twofa_sessions_pkey PRIMARY KEY (id),
    CONSTRAINT twofa_sessions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE,
    CONSTRAINT twofa_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE INDEX if not exists idx_twofa_sessions_lookup ON public.twofa_sessions(tenant_id, user_id);
CREATE INDEX if not exists idx_twofa_sessions_validate ON public.twofa_sessions(tenant_id, id);
CREATE INDEX if not exists idx_twofa_sessions_validity ON public.twofa_sessions(expires_at, revoked_at);

ALTER TABLE public.twofa_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.twofa_sessions FORCE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.twofa_sessions FROM public, anon, authenticated;
GRANT SELECT ON TABLE public.twofa_sessions TO authenticated;

drop policy if exists "Users can see own 2fa sessions" on public.twofa_sessions;
CREATE POLICY "Users can see own 2fa sessions" ON public.twofa_sessions
    FOR SELECT TO authenticated USING (user_id = auth.uid());

-- 3. RPC: create_login_challenge
CREATE OR REPLACE FUNCTION public.create_login_challenge(p_tenant_id uuid)
RETURNS text
LANGUAGE plpgsql security definer set search_path = public, extensions, auth
AS $$
DECLARE
    v_user_id uuid;
    v_code text;
    v_hash text;
    v_is_member boolean;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;

    SELECT EXISTS (SELECT 1 FROM tenant_users tu WHERE tu.tenant_id = p_tenant_id AND tu.user_id = v_user_id) INTO v_is_member;
    IF NOT v_is_member THEN RAISE EXCEPTION 'Access Denied: User is not a member of this tenant'; END IF;

    UPDATE public.login_challenges SET expires_at = now()
    WHERE tenant_id = p_tenant_id AND user_id = v_user_id AND verified_at IS NULL AND expires_at > now();

    v_code := floor(random() * (999999 - 100000 + 1) + 100000)::text;
    IF (SELECT count(*) FROM pg_extension WHERE extname = 'pgcrypto') = 0 THEN CREATE EXTENSION IF NOT EXISTS pgcrypto; END IF;
    v_hash := crypt(v_code, gen_salt('bf'));

    INSERT INTO public.login_challenges (tenant_id, user_id, code_hash, expires_at)
    VALUES (p_tenant_id, v_user_id, v_hash, now() + interval '5 minutes');

    RETURN v_code;
END;
$$;
REVOKE ALL ON FUNCTION public.create_login_challenge(uuid) FROM public, anon;
GRANT EXECUTE ON FUNCTION public.create_login_challenge(uuid) TO authenticated;

-- 4. RPC: verify_login_challenge
CREATE OR REPLACE FUNCTION public.verify_login_challenge(p_tenant_id uuid, p_code text)
RETURNS uuid
LANGUAGE plpgsql security definer set search_path = public, extensions, auth
AS $$
DECLARE
    v_user_id uuid;
    v_record record;
    v_tenant_slug text;
    v_new_session_id uuid;
    v_is_member boolean;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;

    SELECT EXISTS (SELECT 1 FROM tenant_users tu WHERE tu.tenant_id = p_tenant_id AND tu.user_id = v_user_id) INTO v_is_member;
    IF NOT v_is_member THEN RAISE EXCEPTION 'Access Denied: User is not a member of this tenant'; END IF;

    SELECT * INTO v_record FROM public.login_challenges
    WHERE tenant_id = p_tenant_id AND user_id = v_user_id AND verified_at IS NULL AND expires_at > now()
    ORDER BY created_at DESC LIMIT 1;

    IF v_record IS NULL THEN RAISE EXCEPTION 'Invalid or expired code'; END IF;
    IF v_record.code_hash != crypt(p_code, v_record.code_hash) THEN RAISE EXCEPTION 'Invalid code'; END IF;

    UPDATE public.login_challenges SET verified_at = now() WHERE id = v_record.id;
    SELECT slug INTO v_tenant_slug FROM public.tenants WHERE id = p_tenant_id;
    UPDATE public.twofa_sessions SET revoked_at = now() WHERE tenant_id = p_tenant_id AND user_id = v_user_id AND revoked_at IS NULL;

    v_new_session_id := gen_random_uuid();
    INSERT INTO public.twofa_sessions (id, tenant_id, tenant_slug, user_id, expires_at)
    VALUES (v_new_session_id, p_tenant_id, v_tenant_slug, v_user_id, now() + interval '12 hours');

    RETURN v_new_session_id;
END;
$$;
REVOKE ALL ON FUNCTION public.verify_login_challenge(uuid, text) FROM public, anon;
GRANT EXECUTE ON FUNCTION public.verify_login_challenge(uuid, text) TO authenticated;

-- 5. RPC: validate_twofa_session
CREATE OR REPLACE FUNCTION public.validate_twofa_session(p_tenant_id uuid, p_session_id uuid)
RETURNS boolean
LANGUAGE plpgsql security definer set search_path = public, extensions, auth
AS $$
DECLARE v_user_id uuid; v_exists boolean;
BEGIN
    v_user_id := auth.uid();
    SELECT EXISTS (
        SELECT 1 FROM public.twofa_sessions
        WHERE id = p_session_id AND tenant_id = p_tenant_id AND user_id = v_user_id AND revoked_at IS NULL AND expires_at > now()
    ) INTO v_exists;
    RETURN v_exists;
END;
$$;
REVOKE ALL ON FUNCTION public.validate_twofa_session(uuid, uuid) FROM public, anon;
GRANT EXECUTE ON FUNCTION public.validate_twofa_session(uuid, uuid) TO authenticated;


COMMIT;
-- Part 6: Remediation (Appended)
BEGIN;

-- REVOKE ALL on specific strict tables
REVOKE ALL ON TABLE public.groups FROM public, anon;
REVOKE ALL ON TABLE public.organizations FROM public, anon;
REVOKE ALL ON TABLE public.companies FROM public, anon;
REVOKE ALL ON TABLE public.projects FROM public, anon;
REVOKE ALL ON TABLE public.service_offerings FROM public, anon;
REVOKE ALL ON TABLE public.edit_locks FROM public, anon;
REVOKE ALL ON TABLE public.login_challenges FROM public, anon;
REVOKE ALL ON TABLE public.twofa_sessions FROM public, anon;

-- REVOKE ALL on other critical tables (just in case)
REVOKE ALL ON TABLE public.tenants FROM public, anon;
REVOKE ALL ON TABLE public.profiles FROM public, anon;
REVOKE ALL ON TABLE public.roles FROM public, anon;
REVOKE ALL ON TABLE public.permissions FROM public, anon;
REVOKE ALL ON TABLE public.role_permissions FROM public, anon;
REVOKE ALL ON TABLE public.tenant_users FROM public, anon;
REVOKE ALL ON TABLE public.tenant_modules FROM public, anon;

-- Extra paranoid: Revoke on schema public
REVOKE ALL ON SCHEMA public FROM public, anon;
GRANT USAGE ON SCHEMA public TO public, anon; 

COMMIT;

-- ==============================================================================
-- SELF-AUDIT CHECKLIST
-- ==============================================================================
-- Run these queries after applying the migration to verify compliance.

-- 1. Verify RLS is FORCED and ENABLED on new tables
-- SELECT tablename, rowsecurity, force_rls 
-- FROM pg_tables 
-- WHERE tablename IN ('login_challenges', 'twofa_sessions', 'groups', 'organizations', 'companies')
-- AND schemaname = 'public';
-- Expected: rowsecurity=true, force_rls=true for ALL.

-- 2. Verify Security Definer & Search Path on RPCs
-- SELECT proname, prosecdef, proconfig 
-- FROM pg_proc 
-- WHERE proname IN ('create_login_challenge', 'verify_login_challenge', 'validate_twofa_session', 'acquire_edit_lock')
-- AND pronamespace = 'public'::regnamespace;
-- Expected: prosecdef=true (Security Definer), proconfig contains 'search_path=public, auth'

-- 3. Verify Public/Anon cannot read tables directly (Empty results expected for Anon)
-- Note: Function privileges check
-- SELECT grantee, privilege_type 
-- FROM information_schema.role_table_grants 
-- WHERE table_name IN ('login_challenges', 'twofa_sessions')
-- AND grantee IN ('public', 'anon');
-- Expected: NO ROWS found (Revoked All).

-- 4. Verify Function Grants
-- SELECT grantee, routine_name, privilege_type
-- FROM information_schema.routine_privileges
-- WHERE routine_name IN ('create_login_challenge')
-- AND grantee IN ('authenticated');
-- Expected: EXECUTE.

-- 5. Logic Test (Pseudo-Code)
-- call create_login_challenge('invalid-uuid') -> Should Fail (Membership check).
