// mateusz poponczyk
import './globals.css';
import { ReactNode } from 'react';

export const metadata = {
    title: 'Modular Monolith',
    description: 'Generated by Antigravity',
};

export default function RootLayout({
    children,
}: {
    children: ReactNode;
}) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
