// mateusz poponczyk
import './globals.css';
import { ReactNode } from 'react';
import { cookies } from 'next/headers';

export const metadata = {
    title: 'Modular Monolith',
    description: 'Generated by Antigravity',
};

export default async function RootLayout({
    children,
}: {
    children: ReactNode;
}) {
    const cookieStore = await cookies();
    const theme = cookieStore.get('theme')?.value ?? 'system';
    const isDark = theme === 'dark'; // We can't easily know system pref on server, defaulting to light/no-class for now

    return (
        <html lang="en" className={isDark ? 'dark' : ''} suppressHydrationWarning>
            <body className="antialiased">{children}</body>
        </html>
    );
}
